"""Rig and skin a TRELLIS.2 nendoroid hero for glTF/Babylon.js.

This is a variant of ``rig_nendo_character.py`` for sources generated by
TRELLIS.2 instead of SPAR3D. It reuses every step of the shared pipeline
(remesh, decimate, UV project, bone layout, geometric weights, exports) by
dynamically importing that module, but replaces the texture step.

Why a separate texture step: ``rig_nendo_character.py``'s
``bake_turnaround_texture`` re-projects the three-view turnaround reference
image onto the new UVs to fix SPAR3D's unreliable guessed side/back
texture. TRELLIS.2 does not have that problem -- its own generated texture
is already high quality on all sides -- and that reprojection bake (a
custom Cycles node-based UV bake) turns out to leave most small UV islands
as isolated dots rather than filled regions for this mesh's remesh output
(confirmed by inspecting the baked PNG directly: large connected regions
came through fine, but arms/hood/trim -- anything remeshed into many small
islands -- baked as scattered points, which is why glowing circuit-line
details disappeared in-game).

Instead, this script keeps an unmodified copy of the imported TRELLIS.2
mesh (with its original UVs and texture) around after normalization, and
uses Blender's own mature "Selected to Active" Cycles bake to transfer that
texture directly onto the retopologized mesh's new UVs. This is the
standard high-poly-to-low-poly texture transfer workflow and does not
depend on any reference turnaround image at all.

Run from the repository root:

    blender --background --factory-startup --python-exit-code 1 \
        --python scripts/rig_nendo_character_trellis2.py -- hero-nendo-trellis2
"""

from __future__ import annotations

import importlib.util
import math
import sys
from pathlib import Path

import bpy

ROOT_DIR = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT_DIR / "assets" / "production" / "demonic" / "spar3d"
OUTPUT_DIR = ROOT_DIR / "assets" / "production" / "demonic" / "rigged"
BAKE_RESOLUTION = 2048


def log(message: str) -> None:
    print(f"[NENDO_RIG_T2] {message}")


def base_module():
    module_name = "nendo_rig_base"
    if module_name in sys.modules:
        return sys.modules[module_name]
    source = Path(__file__).resolve().parent / "rig_nendo_character.py"
    spec = importlib.util.spec_from_file_location(module_name, source)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load base rig module: {source}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def smooth_for_unwrap(mesh: bpy.types.Object) -> None:
    """Extra coarsening pass, run after the base pipeline's connectivity-focused
    voxel remesh. That remesh only uses the finest voxel size that still yields
    a single connected component, so it preserves every tiny surface bump
    TRELLIS.2 generated (studs, panel gaps, small emblems) -- each of which
    Smart UV Project then treats as a separate high-curvature feature needing
    its own seam/island. The mesh's own visible detail is going to be replaced
    by the baked texture anyway, so none of that fine geometry needs to
    survive into the retopologized mesh; a second, deliberately coarser voxel
    remesh here trades it away in exchange for a smooth, simple surface that
    Smart UV Project can unwrap into a handful of large islands instead of
    thousands of tiny ones.
    """
    height = base_module().bounds_for_mesh(mesh).size.z
    voxel_size = height * 0.018
    base_module().activate_only([mesh], mesh)
    modifier = mesh.modifiers.new("UnwrapSmoothRemesh", "REMESH")
    modifier.mode = "VOXEL"
    modifier.voxel_size = voxel_size
    modifier.adaptivity = 0.0
    bpy.ops.object.modifier_apply(modifier=modifier.name)
    components = base_module().topology_components(mesh)[1]
    log(f"SMOOTH_FOR_UNWRAP voxel_size={voxel_size:.5f} triangles={base_module().triangle_count(mesh)} components={len(components)}")


def smart_uv_project_wide(mesh: bpy.types.Object) -> None:
    """Like the base pipeline's smart_uv_project, but with a much wider angle
    limit. TRELLIS.2's remesh carries far more genuine surface detail than
    SPAR3D's (panel seams, trim, small emblems), and the base 66-degree
    limit splits that detail into thousands of tiny UV islands -- so small
    that no bake (custom or Cycles-native) can paint more than a few pixels
    into each one, which is why the baked texture came out as scattered
    dots. A near-90-degree limit merges far more triangles into fewer,
    larger islands at the cost of more UV stretch, which is the right
    trade here: a slightly warped but continuous texture reads far better
    than a technically-undistorted field of single-pixel dots.
    """
    base_module().activate_only([mesh], mesh)
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    result = bpy.ops.uv.smart_project(angle_limit=math.radians(89.0), island_margin=0.01)
    if "FINISHED" not in result:
        bpy.ops.object.mode_set(mode="OBJECT")
        raise RuntimeError(f"Smart UV Project failed: result={result}")
    # Smart UV Project sizes each island proportionally to its 3D surface
    # area, so small greebles/trim/emblems -- exactly the detail TRELLIS.2
    # renders that SPAR3D didn't -- get a proportionally tiny sliver of UV
    # space no matter the angle limit or bake resolution. average_islands_scale
    # renormalises every island to a common texel density first, so a small
    # part gets UV space proportional to how much *detail* it needs, not how
    # much 3D surface it covers; pack_islands then repacks at that corrected
    # scale. This is the standard fix for exactly this "tiny parts vanish"
    # symptom in high-poly-to-textured workflows.
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.average_islands_scale()
    bpy.ops.uv.pack_islands(margin=0.01)
    bpy.ops.object.mode_set(mode="OBJECT")
    uv_layer = mesh.data.uv_layers.active
    if uv_layer is None or not uv_layer.data:
        raise RuntimeError("Smart UV Project produced no UV data.")
    # Cycles bakes use whichever UV layer is marked active *for render*, which
    # is a separate flag from "active" (used for editing/display). If a stale
    # layer is still render-active, the bake samples the wrong UV data even
    # though everything upstream looks correct.
    uv_layer.active_render = True
    all_uv_names = [layer.name for layer in mesh.data.uv_layers]
    log(f"UV_SMART_PROJECT_WIDE layer={uv_layer.name} loops={len(uv_layer.data)} angle_limit_degrees=89 averaged_and_repacked=True all_uv_layers={all_uv_names} active_render={uv_layer.active_render}")


def duplicate_mesh(mesh: bpy.types.Object, name: str) -> bpy.types.Object:
    duplicate = mesh.copy()
    duplicate.data = mesh.data.copy()
    duplicate.name = name
    bpy.context.collection.objects.link(duplicate)
    return duplicate


def bake_from_source(source_ref: bpy.types.Object, target: bpy.types.Object, name: str) -> Path:
    """Cycles "Selected to Active" bake: source_ref's existing texture onto target's new UVs."""
    if target.data.uv_layers.active is None:
        raise RuntimeError("Cannot bake without a UV map on the target mesh.")

    baked_image = bpy.data.images.new(f"{name}-baked", BAKE_RESOLUTION, BAKE_RESOLUTION, alpha=False)

    # Route the source mesh's existing Base Color texture into Emission on
    # every material it uses, so an EMIT bake (fully independent of scene
    # lighting/shading evaluation) can transfer pure, unlit albedo. A DIFFUSE
    # bake with pass_filter={'COLOR'} should in theory also isolate albedo,
    # but produced the same "mostly black, scattered dot" result regardless
    # of UV island size or triangle count, which points at something in how
    # Cycles evaluates the imported glTF Principled BSDF graph for the
    # DIFFUSE pass rather than a UV/ray-distance problem -- EMIT sidesteps
    # that evaluation entirely.
    for slot in source_ref.material_slots:
        mat = slot.material
        if mat is None or not mat.use_nodes:
            continue
        mat_nodes = mat.node_tree.nodes
        mat_links = mat.node_tree.links
        bsdf_node = next((n for n in mat_nodes if n.type == "BSDF_PRINCIPLED"), None)
        image_node = next((n for n in mat_nodes if n.type == "TEX_IMAGE" and n.image is not None), None)
        if bsdf_node is None or image_node is None:
            continue
        base_color_link = next(
            (link for link in bsdf_node.inputs["Base Color"].links),
            None,
        )
        color_source = base_color_link.from_socket if base_color_link else image_node.outputs["Color"]
        emission_node = mat_nodes.new("ShaderNodeEmission")
        mat_links.new(color_source, emission_node.inputs["Color"])
        output_node = next((n for n in mat_nodes if n.type == "OUTPUT_MATERIAL"), None)
        if output_node is not None:
            mat_links.new(emission_node.outputs["Emission"], output_node.inputs["Surface"])
        log(f"BAKE_PREP material={mat.name} routed_to_emit=True")

    material = bpy.data.materials.new(f"{name}-bake-target")
    material.use_nodes = True
    nodes = material.node_tree.nodes
    nodes.clear()
    output = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Metallic"].default_value = 0.32
    bsdf.inputs["Roughness"].default_value = 0.42
    material.node_tree.links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])
    bake_node = nodes.new("ShaderNodeTexImage")
    bake_node.image = baked_image
    nodes.active = bake_node

    target.data.materials.clear()
    target.data.materials.append(material)

    scene = bpy.context.scene
    original_engine = scene.render.engine
    scene.render.engine = "CYCLES"
    scene.cycles.samples = 8
    original_bake_margin = scene.render.bake.margin
    scene.render.bake.margin = 16

    base_module().activate_only([source_ref, target], target)
    log(f"BAKE_START source={source_ref.name} target={target.name} resolution={BAKE_RESOLUTION}")
    bpy.ops.object.bake(
        type="EMIT",
        use_selected_to_active=True,
        cage_extrusion=0.15,
        max_ray_distance=0.4,
        margin=32,
        margin_type="EXTEND",
    )
    log("BAKE_COMPLETE")

    scene.render.engine = original_engine
    scene.render.bake.margin = original_bake_margin

    output_path = OUTPUT_DIR / f"{name}-rigged-basecolor.png"
    baked_image.filepath_raw = str(output_path)
    baked_image.file_format = "PNG"
    baked_image.save()

    # Swap the bake-only node setup for the lightweight game material, matching
    # rig_nendo_character.py's textured_material() so both pipelines export
    # visually equivalent glTF materials.
    game_material = bpy.data.materials.new(f"{name}-game-material")
    game_material.use_nodes = True
    gm_nodes = game_material.node_tree.nodes
    gm_links = game_material.node_tree.links
    gm_nodes.clear()
    gm_output = gm_nodes.new("ShaderNodeOutputMaterial")
    gm_bsdf = gm_nodes.new("ShaderNodeBsdfPrincipled")
    gm_bsdf.inputs["Metallic"].default_value = 0.32
    gm_bsdf.inputs["Roughness"].default_value = 0.42
    gm_texture = gm_nodes.new("ShaderNodeTexImage")
    gm_texture.image = baked_image
    gm_texture.interpolation = "Linear"
    gm_links.new(gm_texture.outputs["Color"], gm_bsdf.inputs["Base Color"])
    if "Emission Color" in gm_bsdf.inputs and "Emission Strength" in gm_bsdf.inputs:
        gm_links.new(gm_texture.outputs["Color"], gm_bsdf.inputs["Emission Color"])
        gm_bsdf.inputs["Emission Strength"].default_value = 0.12
    gm_links.new(gm_bsdf.outputs["BSDF"], gm_output.inputs["Surface"])
    target.data.materials.clear()
    target.data.materials.append(game_material)

    log(f"BAKE_SAVED path={output_path} bytes={output_path.stat().st_size}")
    return output_path


def requested_name() -> str:
    arguments = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    if len(arguments) != 1:
        raise RuntimeError("Expected exactly one base name, for example: -- hero-nendo-trellis2")
    name = arguments[0]
    if Path(name).name != name or name.endswith(".glb"):
        raise RuntimeError(f"Use a bare GLB base name, not {name!r}")
    return name


def main() -> None:
    base = base_module()
    name = requested_name()
    source_path = SOURCE_DIR / f"{name}.glb"
    if not source_path.is_file():
        raise RuntimeError(f"Missing source GLB: {source_path}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_glb = OUTPUT_DIR / f"{name}-rigged.glb"
    log(f"START blender={bpy.app.version_string} source={source_path}")

    base.clear_scene()
    bpy.ops.import_scene.gltf(filepath=str(source_path))
    mesh = base.remove_staging_and_join()
    base.normalize_mesh(mesh)
    base.log_source_components(mesh)

    source_ref = duplicate_mesh(mesh, f"{name}-bake-source")
    log(f"DUPLICATED source_ref={source_ref.name} for post-remesh baking")

    base.remesh_for_deformation(mesh)
    smooth_for_unwrap(mesh)
    base.decimate_if_needed(mesh)
    smart_uv_project_wide(mesh)
    texture_path = bake_from_source(source_ref, mesh, name)
    bpy.data.objects.remove(source_ref, do_unlink=True)

    layout = base.measured_layout(mesh)
    specs = base.bone_specs(layout)
    armature = base.create_armature(specs)
    base.bind_armature_directly(mesh, armature)
    base.geometric_distance_weights(mesh, specs, layout)
    for label in ("tpose", "arms-up", "elbow", "walk", "crouch"):
        base.render_pose(label, mesh, armature, layout, OUTPUT_DIR / f"pose-{name}-{label}.png")
    base.export_glb(mesh, armature, output_glb)
    log(f"COMPLETE name={name} bones={len(specs)} texture={texture_path} output={output_glb}")


if __name__ == "__main__":
    main()
